apiVersion: policy.sigstore.dev/v1alpha1
kind: ClusterImagePolicy
metadata:
  name: image-policy
spec:
  images:
    - glob: "**"
  authorities:
    - key:
        data: |
          -----BEGIN PUBLIC KEY-----
          MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEDMD5MXolskwQMpGBG1Q8zSr2ID4r
          rPsHABGqnVn/txRG2mYYq9O4RhLxZMXonltv795n1OJ5bvH+DQcVmW3JKg==
          -----END PUBLIC KEY-----